@BaseUrl = http://localhost:8080

# @name getListCourse
GET {{BaseUrl}}/course/list


###


# @name getCourseItem
GET {{BaseUrl}}/course/6


###


# # @name getCourse
# POST {{BaseUrl}}/course
# Content-Type: application/json
# {
#      "poster": "image/avatar/momo.webp",
#      "description": "sang test post server",
# }
# ###